version: "3.8"

services:
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=doub-freshman
      - MONGO_INITDB_ROOT_PASSWORD=Hustonline87542701doub-freshman
      - MONGO_INITDB_DATABASE=doub-freshman
    container_name: doub-freshman_mongo
    expose:
      - "27017"
    networks:
      - doub-freshman
  redis:
    image: redis:4.0.8
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: doub-freshman_redis
    volumes:
      - .data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    networks:
      - doub-freshman
  app:
    image: registry.cn-hangzhou.aliyuncs.com/bingyan/go-web-container:3.0
    environment:
      - TZ=Asia/Shanghai
      - ENV=prod
    ports:
      - "3265:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app
      - ./env:/env
      - ./log:/app/log
    depends_on:
      - mongo
      - redis
    container_name: doub-freshman_app
    networks:
      - doub-freshman
networks:
  doub-freshman:
    driver: overlay
