version: "3.8"

services:
  mongo:
    image: mongo:4.4.6
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=doub-freshman
    container_name: doub-freshman_mongo
    expose:
      - "27017"
    networks:
      - doub-freshman
  redis:
    image: redis:6.2.3
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: doub-freshman_redis
    volumes:
      - .data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    networks:
      - doub-freshman
  app:
    build: .
    environment:
      - TZ=Asia/Shanghai
      - ENV=dev
    ports:
      - "30010:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/app
      - ./env:/env
      - ./log:/app/log
    depends_on:
      - mongo
      - redis
    container_name: doub-freshman_app
    networks:
      - doub-freshman
networks:
  doub-freshman:
    driver: overlay
